select * from STG_BOND_PLEDGE;
create table ray_stg_bond_pledge as SELECT * from STG_BOND_PLEDGE;
select * from STG_BOND_PLEDGE;
drop table STG_BOND_PLEDGE;
CREATE TABLE STG_BOND_PLEDGE
(
  SECURITY_CD    VARCHAR2(100),
  rpt_dt         VARCHAR2(100),
  NOTICE_DT      VARCHAR2(100),
  PLEDGE_NM      VARCHAR2(300),
  PLEDGE_TYPE    VARCHAR2(300),
  PLEDGE_VALUE   VARCHAR2(100),
  PLEDGE_DEPEND  VARCHAR2(100),
  PLEDGE_CONTROL VARCHAR2(100),
  REGION         VARCHAR2(100),
  PRIORITY_VALUE VARCHAR2(100),
  DATA_SRC       VARCHAR2(1000),
  isdel          char(1)
)
/

insert into STG_BOND_PLEDGE
    select
      SECURITY_CD
,null rpt_dt
,NOTICE_DT
,PLEDGE_NM
,PLEDGE_TYPE
,PLEDGE_VALUE
,PLEDGE_DEPEND
,PLEDGE_CONTROL
,REGION
,PRIORITY_VALUE
,DATA_SRC
,0 as isdel
      from ray_stg_bond_pledge;
commit;


create table ray_bond_pledge as select * from BOND_PLEDGE;
drop table BOND_PLEDGE;

CREATE TABLE BOND_PLEDGE
(
  BOND_PLEDGE_SID   NUMBER(16)    NOT NULL,
  SECINNER_ID       NUMBER(16)    NOT NULL,
  rpt_dt            date          not null,
  NOTICE_DT         DATE,
  PLEDGE_NM         VARCHAR2(300) NOT NULL,
  PLEDGE_TYPE_ID    NUMBER(16),
  PLEDGE_DESC       VARCHAR2(2000),
  PLEDGE_OWNER_ID   NUMBER(16),
  PLEDGE_OWNER      VARCHAR2(300),
  PLEDGE_VALUE      NUMBER(20, 4),
  PRIORITY_VALUE    NUMBER(20, 4),
  PLEDGE_DEPEND_ID  NUMBER(16),
  PLEDGE_CONTROL_ID NUMBER(16),
  REGION            NUMBER,
  MITIGATION_VALUE  NUMBER(20, 4),
  ISDEL             NUMBER        NOT NULL,
  SRCID             VARCHAR2(100),
  SRC_CD            VARCHAR2(10)  NOT NULL,
  UPDT_BY           NUMBER(16)    NOT NULL,
  UPDT_DT           TIMESTAMP(6)  NOT NULL
)
/

insert into BOND_PLEDGE
  select
    BOND_PLEDGE_SID
,SECINNER_ID
,date '2016-12-31' as rpt_dt
,NOTICE_DT
,PLEDGE_NM
,PLEDGE_TYPE_ID
,PLEDGE_DESC
,PLEDGE_OWNER_ID
,PLEDGE_OWNER
,PLEDGE_VALUE
,PRIORITY_VALUE
,PLEDGE_DEPEND_ID
,PLEDGE_CONTROL_ID
,REGION
,MITIGATION_VALUE
,ISDEL
,SRCID
,SRC_CD
,UPDT_BY
,UPDT_DT
    from ray_bond_pledge;
commit;


create table RAY_BOND_PLEDGE_todo as select * from BOND_PLEDGE_TODO;
drop table BOND_PLEDGE_TODO;
cREATE TABLE BOND_PLEDGE_TODO
(
  SECURITY_CD    VARCHAR2(100),
  rpt_dt         varchar2(100),
  NOTICE_DT      VARCHAR2(100),
  PLEDGE_NM      VARCHAR2(300),
  PLEDGE_TYPE    VARCHAR2(300),
  PLEDGE_VALUE   VARCHAR2(100),
  PLEDGE_DEPEND  VARCHAR2(100),
  PLEDGE_CONTROL VARCHAR2(100),
  REGION         VARCHAR2(100),
  PRIORITY_VALUE VARCHAR2(100),
  DATA_SRC       VARCHAR2(1000),
  SECINNER_ID    NUMBER(16),
  isdel          char(1)
)
/

insert into BOND_PLEDGE_TODO
    select
      SECURITY_CD
,rpt_dt
,NOTICE_DT
,PLEDGE_NM
,PLEDGE_TYPE
,PLEDGE_VALUE
,PLEDGE_DEPEND
,PLEDGE_CONTROL
,REGION
,PRIORITY_VALUE
,DATA_SRC
,SECINNER_ID
,null as isdel
      from RAY_BOND_PLEDGE_todo;
commit;
