create view vw_bond_warrantor as
select bond_warrantor_sid,
    secinner_id,
    notice_dt,
    warranty_rate,
    guarantee_type_id,
    warranty_period,
    warrantor_id,
    warrantor_nm,
    warrantor_type_id,
    start_dt,
    end_dt,
    warranty_amt,
    warrantor_resume,
    warranty_contract,
    warranty_benef,
    warranty_content,
    warranty_type_id,
    warranty_claim,
    warranty_strength_id,
    pay_step,
    warranty_fee,
    exempt_set,
    warranty_obj,
    isser_credit,
    src_updt_dt,
    mitigation_value,
    isdel,
    srcid,
    src_cd,
    updt_by,
    updt_dt
  from (
  SELECT a.bond_warrantor_sid,
    a.secinner_id,
    COALESCE(a.notice_dt, b.notice_dt) AS notice_dt,
    b.warranty_rate,
    a.guarantee_type_id,
    b.warranty_period,
    COALESCE(a.warrantor_id, b.warrantor_id) AS warrantor_id,
    a.warrantor_nm,
    a.warrantor_type_id,
    b.start_dt,
    b.end_dt,
    COALESCE(a.warranty_amt, b.warranty_amt) AS warranty_amt,
    b.warrantor_resume,
    b.warranty_contract,
    b.warranty_benef,
    b.warranty_content,
    COALESCE(b.warranty_type_id, ((-1))::bigint) AS warranty_type_id,
    b.warranty_claim,
    a.warranty_strength_id,
    b.pay_step,
    b.warranty_fee,
    b.exempt_set,
    b.warranty_obj,
    b.isser_credit,
    b.src_updt_dt,
    NULL::numeric(20,4) AS mitigation_value,
    COALESCE(a.isdel, b.isdel) AS isdel,
    COALESCE(a.srcid, b.srcid) AS srcid,
    COALESCE(a.src_cd, b.src_cd) AS src_cd,
    0 AS updt_by,
    COALESCE(a.updt_dt, b.updt_dt) AS updt_dt,
    a.rpt_dt,
    max(a.rpt_dt)over(partition by a.secinner_id) as max_rpt_dt,
    row_number()over(partition by a.secinner_id, COALESCE(a.warrantor_id, b.warrantor_id),to_char(a.rpt_dt, 'yyyy') order by a.rpt_dt desc, COALESCE(a.updt_dt, b.updt_dt)) as cnt
   FROM (bond_warrantor_expert a
     LEFT JOIN bond_warrantor b ON (((((a.secinner_id = b.secinner_id) AND (a.guarantee_type_id = b.guarantee_type_id)) AND ((a.warrantor_nm)::text = (b.warrantor_nm)::text)) AND (a.warrantor_type_id = b.warrantor_type_id))))) as ret
  where to_char(rpt_dt,'yyyy') = to_char(max_rpt_dt,'yyyy')
   and cnt = 1


