drop table if exists ray_lkp_model_bond_type;
commit;
drop table if exists ray_bond_rating_record;
commit;
drop table if exists ray_bond_rating_factor;
commit;
drop table if exists ray_rating_factor;
commit;
drop table if exists ray_bond_factor_option;
commit;
drop table if exists ray_bond_pledge;
commit;
drop table if exists ray_bond_rating_model;
commit;
drop table if exists ray_lkp_ratingcd_xw;
commit;
drop view if exists ray_vw_bond_rating_cacul;
commit;
drop view if exists ray_vw_bond_rating_cacul_pledge;
commit;
drop view if exists ray_vw_bond_rating_cacul_warrantor;
commit;
