update factor set factor_category_cd=1 where
   factor_cd in ('factor_019','factor_021','factor_052','factor_005','factor_008');
commit;

update factor set formula_en=	'(nvl(nullif((operate_reve-operate_reve_last_y)/operate_reve_last_y,0),(operate_reve_last_y-operate_reve_bf_last_y)/operate_reve_bf_last_y)+nvl(nullif((operate_reve_last_y-operate_reve_bf_last_y)/operate_reve_bf_last_y,0),(operate_reve-operate_reve_last_y)/operate_reve_last_y))/2'	where factor_cd=	'Growth1'	;
update factor set formula_en=	'(nvl(nullif((operate_profit-operate_profit_last_y)/operate_profit_last_y,0),(operate_profit_last_y-operate_profit_bf_last_y)/operate_profit_bf_last_y)+nvl(nullif((operate_profit_last_y-operate_profit_bf_last_y)/operate_profit_bf_last_y,0),(operate_profit-operate_profit_last_y)/operate_profit_last_y))/2'	where factor_cd=	'Growth2'	;
update factor set formula_en=	'(nvl(nullif((sum_profit-sum_profit_last_y)/sum_profit_last_y,0),(sum_profit_last_y-sum_profit_bf_last_y)/sum_profit_bf_last_y)+nvl(nullif((sum_profit_last_y-sum_profit_bf_last_y)/sum_profit_bf_last_y,0),(sum_profit-sum_profit_last_y)/sum_profit_last_y))/2'	where factor_cd=	'Growth3'	;
update factor set formula_en=	'(nvl(nullif((net_profit-net_profit_last_y)/net_profit_last_y,0),(net_profit_last_y-net_profit_bf_last_y)/net_profit_bf_last_y)+nvl(nullif((net_profit_last_y-net_profit_bf_last_y)/net_profit_bf_last_y,0),(net_profit-net_profit_last_y)/net_profit_last_y))/2'	where factor_cd=	'Growth4'	;
update factor set formula_en=	'(nvl(nullif((parent_net_profit-parent_net_profit_last_y)/parent_net_profit_last_y,0),(parent_net_profit_last_y-parent_net_profit_bf_last_y)/parent_net_profit_bf_last_y)+nvl(nullif((parent_net_profit_last_y-parent_net_profit_bf_last_y)/parent_net_profit_bf_last_y,0),(parent_net_profit-parent_net_profit_last_y)/parent_net_profit_last_y))/2'	where factor_cd=	'Growth5'	;
update factor set formula_en=	'(nvl(nullif((ebit-ebit_last_y)/ebit_last_y,0),(ebit_last_y-ebit_bf_last_y)/ebit_bf_last_y)+nvl(nullif((ebit_last_y-ebit_bf_last_y)/ebit_bf_last_y,0),(ebit-ebit_last_y)/ebit_last_y))/2'	where factor_cd=	'Growth6'	;
update factor set formula_en=	'(nvl(nullif((ebitda-ebitda_last_y)/ebitda_last_y,0),(ebitda_last_y-ebitda_bf_last_y)/ebitda_bf_last_y)+nvl(nullif((ebitda_last_y-ebitda_bf_last_y)/ebitda_bf_last_y,0),(ebitda-ebitda_last_y)/ebitda_last_y))/2'	where factor_cd=	'Growth7'	;
update factor set formula_en=	'(nvl(nullif((sum_asset-sum_asset_last_y)/sum_asset_last_y,0),(sum_asset_last_y-sum_asset_bf_last_y)/sum_asset_bf_last_y)+nvl(nullif((sum_asset_last_y-sum_asset_bf_last_y)/sum_asset_bf_last_y,0),(sum_asset-sum_asset_last_y)/sum_asset_last_y))/2'	where factor_cd=	'Growth8'	;
update factor set formula_en=	'(nvl(nullif((sum_sh_equity-sum_sh_equity_last_y)/sum_sh_equity_last_y,0),(sum_sh_equity_last_y-sum_sh_equity_bf_last_y)/sum_sh_equity_bf_last_y)+nvl(nullif((sum_sh_equity_last_y-sum_sh_equity_bf_last_y)/sum_sh_equity_bf_last_y,0),(sum_sh_equity-sum_sh_equity_last_y)/sum_sh_equity_last_y))/2'	where factor_cd=	'Growth9'	;
update factor set formula_en=	'360*(nvl(nullif(inventory_last_y,0),inventory)+nvl(nullif(inventory,0),inventory_last_y))/operate_exp/2+360*(nvl(nullif(account_rec_last_y,0),account_rec)+nvl(nullif(account_rec,0),account_rec_last_y))/operate_reve/2'	where factor_cd=	'Operation1'	;
update factor set formula_en=	'operate_reve*2/(nvl(nullif(fixed_asset_last_y,0),fixed_asset)+nvl(nullif(fixed_asset,0),fixed_asset_last_y))'	where factor_cd=	'Operation10'	;
update factor set formula_en=	'operate_reve*2/(nvl(nullif(sum_nonl_asset_last_y,0),sum_nonl_asset)+nvl(nullif(sum_nonl_asset,0),sum_nonl_asset_last_y))'	where factor_cd=	'Operation11'	;
update factor set formula_en=	'operate_reve*2/(nvl(nullif(sum_asset_last_y,0),sum_asset)+nvl(nullif(sum_asset,0),sum_asset_last_y))'	where factor_cd=	'Operation12'	;
update factor set formula_en=	'360*(nvl(nullif(inventory_last_y,0),inventory)+nvl(nullif(inventory,0),inventory_last_y))/operate_exp/2+360*(nvl(nullif(account_rec_last_y,0),account_rec)+nvl(nullif(account_rec,0),account_rec_last_y))/operate_reve/2-360*(nvl(nullif(account_pay_last_y,0),account_pay)+nvl(nullif(account_pay,0),account_pay_last_y))/operate_exp/2'	where factor_cd=	'Operation2'	;
update factor set formula_en=	'operate_exp*2/(nvl(nullif(inventory_last_y,0),inventory)+nvl(nullif(inventory,0),inventory_last_y))'	where factor_cd=	'Operation3'	;
update factor set formula_en=	'operate_reve*2/(nvl(nullif(account_rec_last_y,0),account_rec)+nvl(nullif(account_rec,0),account_rec_last_y))'	where factor_cd=	'Operation4'	;
update factor set formula_en=	'operate_reve*2/(nvl(nullif(account_rec_last_y,0),account_rec)+nvl(nullif(bill_rec_last_y,0),bill_rec)+nvl(nullif(account_rec,0),account_rec_last_y)+nvl(nullif(bill_rec,0),bill_rec_last_y))'	where factor_cd=	'Operation5'	;
update factor set formula_en=	'operate_exp*2/(nvl(nullif(account_pay_last_y,0),account_pay)+nvl(nullif(account_pay,0),account_pay_last_y))'	where factor_cd=	'Operation6'	;
update factor set formula_en=	'operate_exp*2/(nvl(nullif(account_pay_last_y,0),account_pay)+nvl(nullif(bill_pay_last_y,0),bill_pay)+nvl(nullif(account_pay,0),account_pay_last_y)+nvl(nullif(bill_pay,0),bill_pay_last_y))'	where factor_cd=	'Operation7'	;
update factor set formula_en=	'operate_reve*2/(nvl(nullif(sum_lasset_last_y-sum_lliab_last_y,0),sum_lasset-sum_lliab)+nvl(nullif(sum_lasset-sum_lliab,0),sum_lasset_last_y-sum_lliab_last_y))'	where factor_cd=	'Operation8'	;
update factor set formula_en=	'operate_reve*2/(nvl(nullif(sum_lasset_last_y,0),sum_lasset)+nvl(nullif(sum_lasset,0),sum_lasset_last_y))'	where factor_cd=	'Operation9'	;
update factor set formula_en=	'ebit*2/(nvl(nullif(sum_asset_last_y,0),sum_asset)+nvl(nullif(sum_asset,0),sum_asset_last_y))'	where factor_cd=	'Profitability1'	;
update factor set formula_en=	'net_profit*2/(nvl(nullif(sum_asset_last_y,0),sum_asset)+nvl(nullif(sum_asset,0),sum_asset_last_y))'	where factor_cd=	'Profitability2'	;
update factor set formula_en=	'net_profit*2/(nvl(nullif(sum_sh_equity_last_y,0),sum_sh_equity)+nvl(nullif(sum_sh_equity,0),sum_sh_equity_last_y))'	where factor_cd=	'Profitability3'	;
update factor set formula_en=	'ebit*2/(nvl(nullif(sum_sh_equity_last_y+sum_lliab_last_y-(account_pay_last_y+advance_receive_last_y+salary_pay_last_y+tax_pay_last_y+other_pay_last_y+accrue_expense_last_y+defer_income_oneyear_last_y+other_lliab_last_y)+bond_pay_last_y+lt_borrow_last_y,0),sum_sh_equity+sum_lliab-(account_pay+advance_receive+salary_pay+tax_pay+other_pay+accrue_expense+defer_income_oneyear+other_lliab)+bond_pay+lt_borrow)+nvl(nullif(sum_sh_equity+sum_lliab-(account_pay+advance_receive+salary_pay+tax_pay+other_pay+accrue_expense+defer_income_oneyear+other_lliab)+bond_pay+lt_borrow,0),sum_sh_equity_last_y+sum_lliab_last_y-(account_pay_last_y+advance_receive_last_y+salary_pay_last_y+tax_pay_last_y+other_pay_last_y+accrue_expense_last_y+defer_income_oneyear_last_y+other_lliab_last_y)+bond_pay_last_y+lt_borrow_last_y))'	where factor_cd=	'Profitability4'	;
update factor set formula_en=	'net_profit*2/(nvl(nullif(sum_sh_equity_last_y+sum_lliab_last_y-(account_pay_last_y+advance_receive_last_y+salary_pay_last_y+tax_pay_last_y+other_pay_last_y+accrue_expense_last_y+defer_income_oneyear_last_y+other_lliab_last_y)+bond_pay_last_y+lt_borrow_last_y,0),sum_sh_equity+sum_lliab-(account_pay+advance_receive+salary_pay+tax_pay+other_pay+accrue_expense+defer_income_oneyear+other_lliab)+bond_pay+lt_borrow)+nvl(nullif(sum_sh_equity+sum_lliab-(account_pay+advance_receive+salary_pay+tax_pay+other_pay+accrue_expense+defer_income_oneyear+other_lliab)+bond_pay+lt_borrow,0),sum_sh_equity_last_y+sum_lliab_last_y-(account_pay_last_y+advance_receive_last_y+salary_pay_last_y+tax_pay_last_y+other_pay_last_y+accrue_expense_last_y+defer_income_oneyear_last_y+other_lliab_last_y)+bond_pay_last_y+lt_borrow_last_y))'	where factor_cd=	'Profitability5'	;
update factor set formula_en=	'(nvl(nullif((sum_asset-agent_trade_security-cagent_trade_security-agent_uw_security-sum_asset_last_y+agent_trade_security_last_y+cagent_trade_security_last_y+agent_uw_security_last_y)/(sum_asset_last_y-agent_trade_security_last_y-cagent_trade_security_last_y-agent_uw_security_last_y),0),(sum_asset_last_y-agent_trade_security_last_y-cagent_trade_security_last_y-agent_uw_security_last_y-sum_asset_bf_last_y+agent_trade_security_bf_last_y+cagent_trade_secu_bf_last_y+agent_uw_security_bf_last_y)/(sum_asset_bf_last_y-agent_trade_security_bf_last_y-cagent_trade_secu_bf_last_y-agent_uw_security_bf_last_y))+nvl(nullif((sum_asset_last_y-agent_trade_security_last_y-cagent_trade_security_last_y-agent_uw_security_last_y-sum_asset_bf_last_y+agent_trade_security_bf_last_y+cagent_trade_secu_bf_last_y+agent_uw_security_bf_last_y)/(sum_asset_bf_last_y-agent_trade_security_bf_last_y-cagent_trade_secu_bf_last_y-agent_uw_security_bf_last_y),0),(sum_asset-agent_trade_security-cagent_trade_security-agent_uw_security-sum_asset_last_y+agent_trade_security_last_y+cagent_trade_security_last_y+agent_uw_security_last_y)/(sum_asset_last_y-agent_trade_security_last_y-cagent_trade_security_last_y-agent_uw_security_last_y)))/2'	where factor_cd=	'Secu_Growth1'	;
update factor set formula_en=	'(nvl(nullif((secu_sub_003-secu_sub_003_last_y)/secu_sub_003_last_y,0),(secu_sub_003_last_y-secu_sub_003_bf_last_y)/secu_sub_003_bf_last_y)+nvl(nullif((secu_sub_003_last_y-secu_sub_003_bf_last_y)/secu_sub_003_bf_last_y,0),(secu_sub_003-secu_sub_003_last_y)/secu_sub_003_last_y))/2'	where factor_cd=	'Secu_Growth2'	;
update factor set formula_en=	'(nvl(nullif((secu_sub_011-secu_sub_011_last_y)/secu_sub_011_last_y,0),(secu_sub_011_last_y-secu_sub_011_bf_last_y)/secu_sub_011_bf_last_y)+nvl(nullif((secu_sub_011_last_y-secu_sub_011_bf_last_y)/secu_sub_011_bf_last_y,0),(secu_sub_011-secu_sub_011_last_y)/secu_sub_011_last_y))/2'	where factor_cd=	'Secu_Growth3'	;
update factor set formula_en=	'(nvl(nullif((operate_reve-operate_reve_last_y)/operate_reve_last_y,0),(operate_reve_last_y-operate_reve_bf_last_y)/operate_reve_bf_last_y)+nvl(nullif((operate_reve_last_y-operate_reve_bf_last_y)/operate_reve_bf_last_y,0),(operate_reve-operate_reve_last_y)/operate_reve_last_y))/2'	where factor_cd=	'Secu_Growth4'	;
update factor set formula_en=	'(nvl(nullif((operate_profit-operate_profit_last_y)/operate_profit_last_y,0),(operate_profit_last_y-operate_profit_bf_last_y)/operate_profit_bf_last_y)+nvl(nullif((operate_profit_last_y-operate_profit_bf_last_y)/operate_profit_bf_last_y,0),(operate_profit-operate_profit_last_y)/operate_profit_last_y))/2'	where factor_cd=	'Secu_Growth5'	;
update factor set formula_en=	'(nvl(nullif((sum_profit-sum_profit_last_y)/sum_profit_last_y,0),(sum_profit_last_y-sum_profit_bf_last_y)/sum_profit_bf_last_y)+nvl(nullif((sum_profit_last_y-sum_profit_bf_last_y)/sum_profit_bf_last_y,0),(sum_profit-sum_profit_last_y)/sum_profit_last_y))/2'	where factor_cd=	'Secu_Growth6'	;
update factor set formula_en=	'(nvl(nullif((net_profit-net_profit_last_y)/net_profit_last_y,0),(net_profit_last_y-net_profit_bf_last_y)/net_profit_bf_last_y)+nvl(nullif((net_profit_last_y-net_profit_bf_last_y)/net_profit_bf_last_y,0),(net_profit-net_profit_last_y)/net_profit_last_y))/2'	where factor_cd=	'Secu_Growth7'	;
update factor set formula_en=	'net_profit*2/(nvl(nullif(sum_asset_last_y-agent_trade_security_last_y-cagent_trade_security_last_y-agent_uw_security_last_y,0),sum_asset-agent_trade_security-cagent_trade_security-agent_uw_security)+nvl(nullif(sum_asset-agent_trade_security-cagent_trade_security-agent_uw_security,0),sum_asset_last_y-agent_trade_security_last_y-cagent_trade_security_last_y-agent_uw_security_last_y))'	where factor_cd=	'Secu_Profitability1'	;
update factor set formula_en=	'net_profit*2/(nvl(nullif(secu_sub_003_last_y,0),secu_sub_003)+nvl(nullif(secu_sub_003,0),secu_sub_003_last_y))'	where factor_cd=	'Secu_Profitability2'	;
update factor set formula_en=	'net_profit*2/(nvl(nullif(secu_sub_011_last_y,0),secu_sub_011)+nvl(nullif(secu_sub_011,0),secu_sub_011_last_y))'	where factor_cd=	'Secu_Profitability3'	;
update factor set formula_en=	'(salary_pay+employee_pay-salary_pay_last_y)/operate_reve'	where factor_cd=	'Secu_Profitability7'	;

update factor set description='总资产收益率是指净利润与资产总计的比率，它反映每1元总资产创造的净利润，值越大，盈利能力越强' where factor_cd='factor_123';
   --更新指标：应收账款占比的描述内容
update factor set description='城投企业在参与政府建设过程中的建设款是计入应收账款。应收账款越高表明地方政府对平台的资金占用程度越高，企业的资产质量越差，信用风险越高。' where factor_cd='factor_513';

commit;
