delete from lkp_rating_code_list where 1 = 1;
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (1, 'AAA+', 'Aaa1');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (2, 'AAA', 'Aaa2');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (3, 'AAA-', 'Aaa3');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (4, 'AA+', 'Aa1');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (5, 'AA', 'Aa2');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (6, 'AA-', 'Aa3');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (7, 'A+', 'A1');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (8, 'A', 'A2');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (9, 'A-', 'A3');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (10, 'BBB+', 'Baa1');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (11, 'BBB', 'Baa2');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (12, 'BBB-', 'Baa3');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (13, 'BB+', 'Ba1');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (14, 'BB', 'Ba2');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (15, 'BB-', 'Ba3');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (16, 'B+', 'B1');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (17, 'B', 'B2');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (18, 'B-', 'B3');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (19, 'CCC+', 'Caa1');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (20, 'CCC', 'Caa2');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (21, 'CCC-', 'Caa3');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (22, 'CC', 'Ca');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (23, 'C', 'C');
INSERT INTO public.lkp_rating_code_list (rating_rnk, rating_code, rating_code_moody) VALUES (24, 'D', 'D');
commit;