-- cs_master_test
drop table bond_basicinfo;
-- Create table
create table BOND_BASICINFO
(
  secinner_id        NUMBER(16) not null,
  security_cd        VARCHAR2(20),
  security_nm        VARCHAR2(300) not null,
  security_snm       VARCHAR2(200),
  spell              VARCHAR2(60),
  security_type_id   NUMBER(16),
  issue_year         INTEGER,
  issue_num          INTEGER,
  currency           VARCHAR2(6),
  trade_market_id    NUMBER(16),
  notice_dt          DATE,
  create_dt          DATE,
  public_dt          DATE,
  public_announce_dt DATE,
  issue_dt           DATE,
  frst_value_dt      DATE,
  last_value_dt      DATE,
  puttable_dt        DATE,
  mrty_dt            DATE,
  payment_dt         DATE,
  redem_dt           DATE,
  delist_dt          DATE,
  pay_day            VARCHAR2(100),
  bond_type1_id      NUMBER(16),
  bond_type2_id      NUMBER(16),
  bond_form_id       NUMBER(16),
  other_nature       VARCHAR2(200),
  credit_rating      VARCHAR2(30),
  issue_vol          NUMBER(20,4),
  listvolsz          NUMBER(20,4),
  listvolsh          NUMBER(20,4),
  bond_period        INTEGER,
  par_value          NUMBER(20,4),
  issue_price        NUMBER(20,4),
  coupon_type_cd     INTEGER,
  pay_type_cd        INTEGER,
  pay_desc           VARCHAR2(1000),
  coupon_rule_cd     INTEGER,
  payment_type_cd    INTEGER,
  coupon_rate        NUMBER(20,4),
  floor_rate         NUMBER(20,4),
  bnchmk_spread      NUMBER(20,4),
  bnchmk_id          NUMBER(16),
  rate_desc          VARCHAR2(1600),
  pay_peryear        INTEGER,
  add_rate           NUMBER(20,4),
  puttable_price     NUMBER(20,4),
  expect_rate        VARCHAR2(30),
  issue_type_cd      INTEGER,
  refe_rate          NUMBER(20,4),
  add_issue_num      INTEGER,
  is_cross           INTEGER,
  is_floor_rate      INTEGER,
  is_adjust_type     INTEGER,
  is_redem           INTEGER,
  is_plit_debt       INTEGER,
  is_puttable        INTEGER,
  is_change          INTEGER,
  fwd_rate           NUMBER(20,4),
  redem_price        NUMBER(20,4),
  swaps_cd           VARCHAR2(20),
  tax_rate           NUMBER(20,4),
  coupon_style_cd    INTEGER,
  option_termdes     VARCHAR2(200),
  base_asset         VARCHAR2(1000),
  coupon_method_cd   INTEGER,
  bond_option        VARCHAR2(80),
  credit_typein_id   NUMBER(16),
  credit_typeout_id  NUMBER(16),
  remark             VARCHAR2(2000),
  src_portfolio_cd   VARCHAR2(30),
  isdel              INTEGER not null,
  srcid              VARCHAR2(100),
  src_cd             VARCHAR2(10) not null,
  updt_by            NUMBER(16) not null,
  updt_dt            TIMESTAMP(6) not null
);
-- Create/Recreate primary, unique and foreign key constraints
alter table BOND_BASICINFO
  add constraint PK_BOND_BASICINFO primary key (SECINNER_ID);

-- CS_MASTER_REHEARSAL_STG
DROP TABLE STG_BOND_BASICINFO;
-- Create table
create table STG_BOND_BASICINFO
(
  record_sid         NUMBER(16),
  secinner_id        NUMBER(16) not null,
  security_cd        VARCHAR2(20),
  security_nm        VARCHAR2(300) not null,
  security_snm       VARCHAR2(200),
  spell              VARCHAR2(60),
  security_type_id   NUMBER(16),
  issue_year         INTEGER,
  issue_num          INTEGER,
  currency           VARCHAR2(6),
  trade_market_id    NUMBER(16),
  notice_dt          DATE,
  create_dt          DATE,
  public_dt          DATE,
  public_announce_dt DATE,
  issue_dt           DATE,
  frst_value_dt      DATE,
  last_value_dt      DATE,
  puttable_dt        DATE,
  mrty_dt            DATE,
  payment_dt         DATE,
  redem_dt           DATE,
  delist_dt          DATE,
  pay_day            VARCHAR2(100),
  bond_type1_id      NUMBER(16),
  bond_type2_id      NUMBER(16),
  bond_form_id       NUMBER(16),
  other_nature       VARCHAR2(200),
  credit_rating      VARCHAR2(30),
  issue_vol          NUMBER(20,4),
  listvolsz          NUMBER(20,4),
  listvolsh          NUMBER(20,4),
  bond_period        INTEGER,
  par_value          NUMBER(20,4),
  issue_price        NUMBER(20,4),
  coupon_type_cd     INTEGER,
  pay_type_cd        INTEGER,
  pay_desc           VARCHAR2(1000),
  coupon_rule_cd     INTEGER,
  payment_type_cd    INTEGER,
  coupon_rate        NUMBER(20,4),
  floor_rate         NUMBER(20,4),
  bnchmk_spread      NUMBER(20,4),
  bnchmk_id          NUMBER(16),
  rate_desc          VARCHAR2(1600),
  pay_peryear        INTEGER,
  add_rate           NUMBER(20,4),
  puttable_price     NUMBER(20,4),
  expect_rate        VARCHAR2(30),
  issue_type_cd      INTEGER,
  refe_rate          NUMBER(20,4),
  add_issue_num      INTEGER,
  is_cross           INTEGER,
  is_floor_rate      INTEGER,
  is_adjust_type     INTEGER,
  is_redem           INTEGER,
  is_plit_debt       INTEGER,
  is_puttable        INTEGER,
  is_change          INTEGER,
  fwd_rate           NUMBER(20,4),
  redem_price        NUMBER(20,4),
  swaps_cd           VARCHAR2(20),
  tax_rate           NUMBER(20,4),
  coupon_style_cd    INTEGER,
  option_termdes     VARCHAR2(200),
  base_asset         VARCHAR2(1000),
  coupon_method_cd   INTEGER,
  bond_option        VARCHAR2(80),
  credit_typein_id   NUMBER(16),
  credit_typeout_id  NUMBER(16),
  remark             VARCHAR2(2000),
  src_portfolio_cd   VARCHAR2(30),
  isdel              INTEGER not null,
  srcid              VARCHAR2(100),
  src_cd             VARCHAR2(10) not null,
  updt_by            NUMBER(16) not null,
  updt_dt            TIMESTAMP(6) not null,
  loadlog_sid        NUMBER(16)
);
-- CS_MASTER_REHEARSAL_STG

DROP TABLE HIST_BOND_BASICINFO;
-- Create table
create table HIST_BOND_BASICINFO
(
  record_sid         NUMBER(16),
  secinner_id        NUMBER(16) not null,
  security_cd        VARCHAR2(20),
  security_nm        VARCHAR2(300) not null,
  security_snm       VARCHAR2(200),
  spell              VARCHAR2(60),
  security_type_id   NUMBER(16),
  issue_year         INTEGER,
  issue_num          INTEGER,
  currency           VARCHAR2(6),
  trade_market_id    NUMBER(16),
  notice_dt          DATE,
  create_dt          DATE,
  public_dt          DATE,
  public_announce_dt DATE,
  issue_dt           DATE,
  frst_value_dt      DATE,
  last_value_dt      DATE,
  puttable_dt        DATE,
  mrty_dt            DATE,
  payment_dt         DATE,
  redem_dt           DATE,
  delist_dt          DATE,
  pay_day            VARCHAR2(100),
  bond_type1_id      NUMBER(16),
  bond_type2_id      NUMBER(16),
  bond_form_id       NUMBER(16),
  other_nature       VARCHAR2(200),
  credit_rating      VARCHAR2(30),
  issue_vol          NUMBER(20,4),
  listvolsz          NUMBER(20,4),
  listvolsh          NUMBER(20,4),
  bond_period        INTEGER,
  par_value          NUMBER(20,4),
  issue_price        NUMBER(20,4),
  coupon_type_cd     INTEGER,
  pay_type_cd        INTEGER,
  pay_desc           VARCHAR2(1000),
  coupon_rule_cd     INTEGER,
  payment_type_cd    INTEGER,
  coupon_rate        NUMBER(20,4),
  floor_rate         NUMBER(20,4),
  bnchmk_spread      NUMBER(20,4),
  bnchmk_id          NUMBER(16),
  rate_desc          VARCHAR2(1600),
  pay_peryear        INTEGER,
  add_rate           NUMBER(20,4),
  puttable_price     NUMBER(20,4),
  expect_rate        VARCHAR2(30),
  issue_type_cd      INTEGER,
  refe_rate          NUMBER(20,4),
  add_issue_num      INTEGER,
  is_cross           INTEGER,
  is_floor_rate      INTEGER,
  is_adjust_type     INTEGER,
  is_redem           INTEGER,
  is_plit_debt       INTEGER,
  is_puttable        INTEGER,
  is_change          INTEGER,
  fwd_rate           NUMBER(20,4),
  redem_price        NUMBER(20,4),
  swaps_cd           VARCHAR2(20),
  tax_rate           NUMBER(20,4),
  coupon_style_cd    INTEGER,
  option_termdes     VARCHAR2(200),
  base_asset         VARCHAR2(1000),
  coupon_method_cd   INTEGER,
  bond_option        VARCHAR2(80),
  credit_typein_id   NUMBER(16),
  credit_typeout_id  NUMBER(16),
  remark             VARCHAR2(2000),
  src_portfolio_cd   VARCHAR2(30),
  isdel              INTEGER not null,
  srcid              VARCHAR2(100),
  src_cd             VARCHAR2(10) not null,
  updt_by            NUMBER(16) not null,
  updt_dt            TIMESTAMP(6) not null,
  loadlog_sid        NUMBER(16)
);
