create sequence seq_investment_limit_ratio ;

insert into INVESTMENT_LIMIT_RATIO
SELECT seq_investment_limit_ratio.nextval as limit_ratio_sid,
      exposure_sid,rating,ratio,isdel,client_id,updt_by,updt_dt
  FROM (select 6344 as exposure_sid,'aaa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6344 as exposure_sid,'aa+' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6344 as exposure_sid,'aa' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6344 as exposure_sid,'aa-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6344 as exposure_sid,'a+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6344 as exposure_sid,'a' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6344 as exposure_sid,'a-' as rating,0.18 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6344 as exposure_sid,'bbb+' as rating,0.16 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6344 as exposure_sid,'bbb' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6344 as exposure_sid,'bbb-' as rating,0.13 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6344 as exposure_sid,'bb+' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6344 as exposure_sid,'bb' as rating,0.08 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6344 as exposure_sid,'bb-' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6344 as exposure_sid,'b' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6344 as exposure_sid,'ccc' as rating,0.02 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6344 as exposure_sid,'cc' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6344 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'aaa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'aa+' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'aa' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'aa-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'a+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'a' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'a-' as rating,0.18 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'bbb+' as rating,0.16 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'bbb' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'bbb-' as rating,0.13 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'bb+' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'bb' as rating,0.08 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'bb-' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'b' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'ccc' as rating,0.02 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'cc' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6354 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'aaa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'aa+' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'aa' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'aa-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'a+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'a' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'a-' as rating,0.18 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'bbb+' as rating,0.16 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'bbb' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'bbb-' as rating,0.13 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'bb+' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'bb' as rating,0.08 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'bb-' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'b' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'ccc' as rating,0.02 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'cc' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6355 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'aaa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'aa+' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'aa' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'aa-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'a+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'a' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'a-' as rating,0.18 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'bbb+' as rating,0.16 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'bbb' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'bbb-' as rating,0.13 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'bb+' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'bb' as rating,0.08 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'bb-' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'b' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'ccc' as rating,0.02 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'cc' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6359 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'aaa' as rating,0.35 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'aa+' as rating,0.32 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'aa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'aa-' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'a+' as rating,0.26 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'a' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'a-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'bbb+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'bbb' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'bbb-' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'bb+' as rating,0.12 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'bb' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'bb-' as rating,0.05 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'b' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'ccc' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'cc' as rating,0.01 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6360 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'aaa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'aa+' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'aa' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'aa-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'a+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'a' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'a-' as rating,0.18 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'bbb+' as rating,0.16 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'bbb' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'bbb-' as rating,0.13 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'bb+' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'bb' as rating,0.08 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'bb-' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'b' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'ccc' as rating,0.02 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'cc' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6368 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'aaa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'aa+' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'aa' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'aa-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'a+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'a' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'a-' as rating,0.18 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'bbb+' as rating,0.16 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'bbb' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'bbb-' as rating,0.13 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'bb+' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'bb' as rating,0.08 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'bb-' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'b' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'ccc' as rating,0.02 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'cc' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6369 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'aaa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'aa+' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'aa' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'aa-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'a+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'a' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'a-' as rating,0.18 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'bbb+' as rating,0.16 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'bbb' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'bbb-' as rating,0.13 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'bb+' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'bb' as rating,0.08 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'bb-' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'b' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'ccc' as rating,0.02 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'cc' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6370 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'aaa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'aa+' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'aa' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'aa-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'a+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'a' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'a-' as rating,0.18 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'bbb+' as rating,0.16 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'bbb' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'bbb-' as rating,0.13 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'bb+' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'bb' as rating,0.08 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'bb-' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'b' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'ccc' as rating,0.02 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'cc' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6372 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'aaa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'aa+' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'aa' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'aa-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'a+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'a' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'a-' as rating,0.18 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'bbb+' as rating,0.16 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'bbb' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'bbb-' as rating,0.13 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'bb+' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'bb' as rating,0.08 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'bb-' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'b' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'ccc' as rating,0.02 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'cc' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6373 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'aaa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'aa+' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'aa' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'aa-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'a+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'a' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'a-' as rating,0.18 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'bbb+' as rating,0.16 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'bbb' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'bbb-' as rating,0.13 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'bb+' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'bb' as rating,0.08 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'bb-' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'b' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'ccc' as rating,0.02 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'cc' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6374 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'aaa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'aa+' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'aa' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'aa-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'a+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'a' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'a-' as rating,0.18 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'bbb+' as rating,0.16 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'bbb' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'bbb-' as rating,0.13 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'bb+' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'bb' as rating,0.08 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'bb-' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'b' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'ccc' as rating,0.02 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'cc' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6375 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'aaa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'aa+' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'aa' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'aa-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'a+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'a' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'a-' as rating,0.18 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'bbb+' as rating,0.16 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'bbb' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'bbb-' as rating,0.13 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'bb+' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'bb' as rating,0.08 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'bb-' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'b' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'ccc' as rating,0.02 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'cc' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6376 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'aaa' as rating,0.35 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'aa+' as rating,0.32 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'aa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'aa-' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'a+' as rating,0.26 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'a' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'a-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'bbb+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'bbb' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'bbb-' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'bb+' as rating,0.12 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'bb' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'bb-' as rating,0.05 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'b' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'ccc' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'cc' as rating,0.01 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6377 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'aaa' as rating,0.35 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'aa+' as rating,0.32 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'aa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'aa-' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'a+' as rating,0.26 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'a' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'a-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'bbb+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'bbb' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'bbb-' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'bb+' as rating,0.12 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'bb' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'bb-' as rating,0.05 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'b' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'ccc' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'cc' as rating,0.01 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6378 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'aaa' as rating,0.35 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'aa+' as rating,0.32 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'aa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'aa-' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'a+' as rating,0.26 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'a' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'a-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'bbb+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'bbb' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'bbb-' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'bb+' as rating,0.12 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'bb' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'bb-' as rating,0.05 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'b' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'ccc' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'cc' as rating,0.01 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6379 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'aaa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'aa+' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'aa' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'aa-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'a+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'a' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'a-' as rating,0.18 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'bbb+' as rating,0.16 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'bbb' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'bbb-' as rating,0.13 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'bb+' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'bb' as rating,0.08 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'bb-' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'b' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'ccc' as rating,0.02 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'cc' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6380 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'aaa' as rating,0.35 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'aa+' as rating,0.32 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'aa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'aa-' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'a+' as rating,0.26 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'a' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'a-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'bbb+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'bbb' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'bbb-' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'bb+' as rating,0.12 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'bb' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'bb-' as rating,0.05 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'b' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'ccc' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'cc' as rating,0.01 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 6381 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'aaa' as rating,0.35 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'aa+' as rating,0.32 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'aa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'aa-' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'a+' as rating,0.26 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'a' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'a-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'bbb+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'bbb' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'bbb-' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'bb+' as rating,0.12 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'bb' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'bb-' as rating,0.05 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'b' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'ccc' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'cc' as rating,0.01 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 60001 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'aaa' as rating,0.3 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'aa+' as rating,0.28 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'aa' as rating,0.25 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'aa-' as rating,0.23 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'a+' as rating,0.21 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'a' as rating,0.2 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'a-' as rating,0.18 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'bbb+' as rating,0.16 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'bbb' as rating,0.15 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'bbb-' as rating,0.13 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'bb+' as rating,0.1 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'bb' as rating,0.08 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'bb-' as rating,0.04 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'b' as rating,0.03 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'ccc' as rating,0.02 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'cc' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual union all
select 0 as exposure_sid,'c' as rating,0 as ratio,0 as isdel, 5 as client_id,123 as updt_by,Systimestamp as updt_dt From dual

);
